### PR TITLE
feat: bootstrap data model for challenges

### PR DESCRIPTION
**Pull request by bobeal**

### CODE REVIEW

**Comment by bobeal** [comment]
@junjou for a first feeback:
- added data model for quiz (and questions)
- not sure what is the meaning of the attributes in the `CustomQuestion` type

**Comment by junjou** [comment]
From what I saw in the code, we are missing the "Actions" contained in the Challenge as well. 
It is basically just selecting an Ecogesture to apply as objective for 2 or 3 days. At the end of the period, it is evaluated for success or fail. It's what I saw for the first challenge. Not sure if it's always the same.

**Comment by bobeal** [comment]
> From what I saw in the code, we are missing the "Actions" contained in the Challenge as well.

Are they really part of challenges? Because I don't see them linked / referenced from the existing challenges.

**Comment by junjou** [comment]
Probably because they are linked dynamically. The user is proposed one by default, but he can pick another one from a list of available ones: ecogestures with an "action" attribute set at `true` and a duration. 

I have updated the data model accordingly

**Comment by junjou** [comment]
Not all Ecogestures are available as actions. I've added some attributes to differentiate them

**Review by junjou — APPROVED** [review]

**Pull request merged**
